name: PR comment
on:
  pull_request_target:
    types: [opened]
    branches:
      - fork
jobs: # Disabled because we cannot build changes from fork PRs using this repo's secrets due to Github limitations. So, the built apk will be from wrong code, so this is pointless.
  comment-on-pr:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.pull_request.title), '[skip ci]')"
    steps:
      - name: Comment on PR with link to checks page
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            ### Download the built apks
            You can download the apks built by Github actions **after** the CI checks pass.
            Please go to the <a href="${{ github.event.pull_request.html_url }}/checks">checks page for this PR</a> to find the zipped apk files under the artifacts drop-down, as seen in the example screenshot below.

            Note that you will have to click on the "Android build PR" tab on the left side to see the artifacts.

            <img src="https://raw.githubusercontent.com/fork-maintainers/iceraven-browser/fork/.github/imgs/download-artifacts-screenshot.png" />
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: false
